### ISSUE TITLE
Remove torrent after certain time

### ISSUE THREAD

**Issue by Er-rchydy** [DiegoRBaquero/uWebTorrentTracker#31]
I want to use `uWebTorrentTracker` as a tracker for live streaming, that means every file (10 seconds length) and all peers related to it who is 2 minutes old should be removed to free the space for the next files.
because for example 2000 viewer is watching a live stream, that means 2000 peers for every HLS segment of 10 seconds, that lead as to 2000*6= 12000 row of data that the server needs to store every single minute, 120,000 row of data in just 10 minutes and so on.
so i'm wondering if there are a way to remove files older than 2 minutes.
thanks

**Comment by DiegoRBaquero** [comment]
Swarms and peers are LRU cached, shouldn't be an issue.

**Comment by DiegoRBaquero** [comment]
I'd say 2 cores, 2GB RAM and 100mpbs

**Comment by Er-rchydy** [comment]
@DiegoRBaquero my last question, is there a big difference between VPS providers because i notice a huge difference in price (some cost $3 others $15)
what's the best operating system to install this tracker?

**Comment by DiegoRBaquero** [comment]
Yes, specially if they use OpenVZ instead of Xen/HVM.

I'd suggest Vultr, which is the one I use for BTorrent's tracker: http://www.vultr.com/?ref=7598017 (It's a ref link and I'd appreciate you use it :) )

Other option I can recommend is Digital Ocean: https://m.do.co/c/0b25a910e6e4

About the OS, I'd go with Ubuntu :)

**Comment by Er-rchydy** [comment]
ok thanks, and of course i will purchase using your referral link no problem :)
